# Generated by Django 3.0.6 on 2020-08-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_auto_20200831_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='This is a Post'),
            preserve_default=False,
        ),
    ]
